# Generated by Django 2.1 on 2018-08-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readbooks', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readbooks.books'),
        ),
        migrations.AddField(
            model_name='review',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readbooks.User'),
        ),
    ]
